services:
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: orders
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      deploy:
        resources:
          reservations:
            cpus: "0.25"
            memory: 1024M
          limits:
            cpus: "0.5"
            memory: 2048M
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 1s
        retries: 3
        start_period: 30s
      ports:
        - "5432:5432"